config/routes.rb
Rails.application.routes.draw do
  get 'policy_pepole/index'
  get 'person_policy/:mp/:id' => 'policy_pepole#index', as: :show_person_policy 
  get 'policy_divisions/:id/edit' => 'policy_divisions#edit', as: :edit_policy_division
  get 'policy_divisions/:date/:id' => 'policy_divisions#new', as: :new_policy_division
  get 'policy_divisions/:date/:id/policy' => 'policy_divisions#policy', as: :get_policy_division
  resources :policy_divisions
  get 'policies/policy', as: :policies_next
  get 'policies/history/:id' => 'policies#history', as: :history_policy
  resources :policies
  devise_for :users, controllers: { sessions: 'users/sessions', passwords: 'users/passwords', registrations: 'users/registrations', confirmations: 'users/confirmations'  }, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  devise_scope :user do
    get '/auth/new_reg', to: "users/registrations#new_reg"
    get '/auth/history', to: "users/registrations#history"
    get '/auth/histories/:user_id', to: "users/registrations#history", as: :user_history
  end
  get 'api/divisions'
  get 'api/division'
  get 'api/policies'
  get 'api/policy'
  get 'api/mp'
  get 'api/mps'

  get 'errors/not_found'

  get 'errors/unacceptable'

  get 'errors/internal_error'

  get 'sumisne-holosuvannia' => 'sumisne_holosuvannia#init', as: :sumisne_holosuvannia
  get 'sumisne-holosuvannia/api' => 'sumisne_holosuvannia#api', as: :sumisne_holosuvannia_api

  get 'help/faq'

  get 'help/data'

  get 'help/licencing'

  get 'divisions' => 'divisions#index', as: :divisions
  get 'divisions/page', as: :divisions_next
  get 'divisions/:date/:id' => 'divisions#show', as: :divisions_show

  get 'people' => 'people#index', as: :people
  get 'people/page', as: :people_next
  get 'people/:mp' => 'people#show', as: :show_people
  get 'people/:mp/divisions' => 'people#divisions', as: :people_divisions
  get 'people/:mp/friends' => 'people#friends', as: :people_friends
  get 'people/:mp/policy' => 'people#policy', as: :people_policy
  get 'people/detal/:mp' => 'people#detal', as: :people_detal

  get 'about' => 'about#index', as: :about
  get 'search_mp' => 'home#search_mp', as: :search_mp
  get 'search' => 'home#search', as: :search
  get 'home/index'
  get "/404", :to => "errors#not_found"
  get "/422", :to => "errors#unacceptable"
  get "/500", :to => "errors#internal_error"

   root 'home#index'

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  #Deputies
  def index
    mps = Mp.includes(:mp_info).where(end_date: '9999-12-31')
    @mp = mps.order(:last_name)
    if params[:sort] == "faction"
      @filter = mps.order(:faction).map{|m| m.faction }.uniq
      if params[:filter].nil?
        params[:filter] = @filter.first
      end
    elsif params[:sort] == "distric"
      @filter = mps.order(:okrug).map{|m| m.okrug }.uniq.compact
      if params[:filter].nil?
        params[:filter] = @filter.first
      end
    elsif params[:sort] == "rebellions"
      if params[:filter_min].nil? or params[:filter_min].blank?
        params[:filter_min] = 30
      end
      if params[:filter_max].nil? or params[:filter_max].blank?
        params[:filter_max] = 90
      end
    elsif params[:sort] == "attendance"
      if params[:filter_min].nil? or params[:filter_min].blank?
        params[:filter_min] = 30
      end
      if params[:filter_max].nil? or params[:filter_max].blank?
        params[:filter_max] = 90
      end
    else
      @filter = mps.order(:last_name).map{|m| m.last_name[0] }.uniq
      if params[:filter].nil?
        params[:filter] = @filter.first
      end
    end
    @mps = mps()
    respond_to do |format|
      format.html
      format.js
    end
  end
  def mps
    if params[:per].nil?
      params[:per] = 8
    end
    mps = Mp.includes(:mp_info).where(end_date: '9999-12-31').where('mp_infos.date_mp_info =  ?','9999-12-31').references(:mp_info)
    if params[:sort] == "faction"
      @mps = mps.where(faction: params[:filter]).order(:faction, :last_name, :first_name, :middle_name, :okrug).page(params[:page]).per(params[:per])
    elsif params[:sort] == "distric"
      @mps = mps.where(okrug: params[:filter]).order(:okrug, :last_name, :first_name, :middle_name, :faction).page(params[:page]).per(params[:per])
    elsif params[:sort] == "rebellions"
      mpls = mps.to_a.find_all{|m| m.mp_info.rebellions_fraction.to_f >= params[:filter_min].to_f/100 and m.mp_info.rebellions_fraction.to_f <= params[:filter_max].to_f/100 }.sort_by{ |m| [-(m.mp_info.rebellions_fraction || -1), m.last_name, m.first_name, m.middle_name, m.faction, m.okrug ]}
    elsif params[:sort] == "attendance"
      mpls = mps.to_a.find_all{|m| m.mp_info.attendance_fraction.to_f >= params[:filter_min].to_f/100 and m.mp_info.attendance_fraction.to_f <= params[:filter_max].to_f/100 }.sort_by{ |m| [-(m.mp_info.attendance_fraction || -1), m.last_name, m.first_name, m.middle_name, m.faction, m.okrug ]}
    else
      @mps = mps.where("last_name like ?", params[:filter] + "%" ).order(:last_name, :first_name, :middle_name, :faction, :okrug).page(params[:page]).per(params[:per])
    end
    if mpls
      @mps = Kaminari.paginate_array(mpls).page(params[:page]).per(params[:per])
    end
    return @mps
  end
  def page
    @mps = mps()
    respond_to do |format|
      format.js
    end
  end
  #Deputy
  def show
    if params[:month].nil? or  params[:month].blank?
      params[:month] = "full"
    end
    @month = MpInfo.pluck(:date_mp_info).uniq.sort{|x, y| y <=> x } .to_a.delete_if{|m| m.strftime('%Y-%m-%d') == '9999-12-31'}

    @division = get_mp()

  end
  def detal
    @division = get_mp()
    if request.format.html?
      redirect_to show_people_path(params)
    end
  end
  def get_mp
    mp_find = params[:mp].split("_")
    if not params[:month].nil? and params[:month] != "full"
      mp_date = (Date.strptime(params[:month], '%Y-%m'))
      p mp_date
    else
      mp_date = "9999-12-31"
    end
    @mp = Mp.includes(:mp_info).where(last_name: mp_find[0], first_name: mp_find[1], middle_name: mp_find[2]).where('mp_infos.date_mp_info = ?',  mp_date).references(:mp_info).last
    if @mp
      if params[:vote] == "friends"
        return get_friends(@mp.id)
      elsif params[:vote] == "policy"
        return get_policy(@mp.deputy_id)
      else
        return get_divisions(@mp.id, @mp.faction)
      end
    else
      redirect_to people_path, :notice => "Не занйдено #{mp_find.join(" ")}"
    end
  end

  def get_policy(deputy_id)
    if params[:policy].nil?
      params[:policy] = "1"
    end
    @policies = Policy.includes(:policy_divisions).joins(:policy_person_distances).where("policy_person_distances.deputy_id=?", deputy_id ).filter_polices(params[:policy]).page(params[:page]).per(6)
  end
  def get_divisions(deputy_id, faction)
    division = Division.includes(:division_info).joins(:votes, :whips).where('votes.deputy_id =? and whips.party=?', deputy_id, faction ).order(date: :desc, id: :desc).references(:division_info)
    if not params[:month].nil? and params[:month] != "full"
    division = division.where("date >= ? AND date < ?", Date.strptime(params[:month], '%Y-%m'), Date.strptime(params[:month], '%Y-%m') + 1.month)
    end
    divisions =
        case params[:vote]
          when "last_vote"
            division.page(params[:page]).per(6)
          else
            division.where('votes.vote != whips.whip_guess and votes.vote != ?', "absent").page(params[:page]).per(6)
        end
    return divisions
  end
  def get_friends(deputy_id)
    if not params[:month].nil? and params[:month] != "full"
      friends = MpFriend.where(deputy_id: deputy_id, date_mp_friend: Date.strptime(params[:month], '%Y-%m') ).order(count: :desc)
    else
      friends = MpFriend.where(deputy_id: deputy_id, date_mp_friend: "9999-12-31" ).order(count: :desc)
    end
    friends.page(params[:page]).per(5)
  end
  def divisions
    @division = get_mp()
  end
  def friends
    @friends = get_mp()
  end
  def policy
    @friends = get_mp()
  end
end

app/views/people/_detal.erb
<div class="col-12 list-filters clearfix d-none d-sm-none d-md-none d-lg-block">
  <ul class="sort-first text-uppercase">
    <li <%= params[:vote].blank? ? "class=disabled": "" %>><%= link_to "Голосування проти фракції", people_detal_path(@mp.url_name, month: params[:month] ), remote: true %></li>
    <li <%= params[:vote] == "last_vote" ? "class=disabled": "" %>><%= link_to "Останні голосування", people_detal_path(@mp.url_name, vote: "last_vote", month: params[:month]), remote: true %></li>
    <li <%= params[:vote] == "friends" ? "class=disabled": "" %>><%= link_to "Друзі по голосуванню", people_detal_path(@mp.url_name, vote: "friends", month: params[:month] ), remote: true %></li>
    <li <%= params[:vote] == "policy" ? "class=disabled": "" %>><%= link_to "Політики", people_detal_path(@mp.url_name, vote: "policy" ), remote: true %></li>
  </ul>
</div>
  <select class="mobile_select d-block d-md-none" onchange="window.location.href=this.value;">
      <option  <%= params[:vote].blank? ? 'selected="selected"': ''%> value="<%=people_detal_path(@mp.url_name, month: params[:month]) %>">Голосування проти фракції</option>
      <option <%= params[:vote] == "last_vote" ? 'selected="selected"': ''%> value="<%=people_detal_path(@mp.url_name, vote: "last_vote", month: params[:month])%>">Останні голосування</option>
      <option <%= params[:sort] == "friends" ? 'selected="selected"': ''%> value="<%=people_detal_path(@mp.url_name, vote: "friends", month: params[:month])%>">Друзі по голосуванню</option>
      <option <%= params[:vote] == "policy" ? 'selected="selected"': ''%> value="<%=people_detal_path(@mp.url_name, vote: "policy" )%>">Політики</option>	
  </select>



<% if params[:vote] == "last_vote" %>
    <p class="text-xs-center ">Голосування в яких депутат міг взяти участь</p>
    <div id="list_vote">
      <%= render "voted", division: @division, mp: @mp  %>
    </div>
<% elsif params[:vote] == "friends"  %>
    <p class="text-xs-center ">Депутати, що голосують подібно. Таким чином, можна виявити
      неочікуваний зв’язок між політичними позиціями депутатів.</p>
    <div id="friend" class="container">
      <div class="row head">
        <div class="col-3">Спільних голосувань</div>
        <div class="col-3">Депутат</div>

        <div class="col-3">Округ</div>
        <div class="col-3">Фракція</div>
      </div>
      <div id="list_vote">
        <%= render "friends", friends: @division, mp: @mp  %>
      </div>
    </div>
<% elsif params[:vote] == "policy"  %>
    <div class="col-11 list-filters">
      <ul class="sort-fraction text-uppercase d-none d-sm-none d-md-none d-lg-block">
        <div style="display: flex; justify-content: left; -webkit-flex-flow: row wrap">
          <li class="<%= params[:policy] == "1"  ? "active-fon-fraction": "non-active-fon-fraction" %>"><%= link_to "Максимально голосує за", people_detal_path(@mp.url_name, vote: "policy"  ), remote: true %></li>
          <li class="<%= params[:policy] == "2" ? "active-fon-fraction": "non-active-fon-fraction" %>"><%= link_to "Послідовно голосує за", people_detal_path(@mp.url_name, vote: "policy", policy: 2), remote: true %></li>
          <li class="<%= params[:policy] == "3" ? "active-fon-fraction": "non-active-fon-fraction" %>"><%= link_to "Переважно голосує за", people_detal_path(@mp.url_name, vote: "policy", policy: 3 ), remote: true %></li>
          <li class="<%= params[:policy] == "4" ? "active-fon-fraction": "non-active-fon-fraction" %>"><%= link_to "Суміш за та проти", people_detal_path(@mp.url_name, vote: "policy", policy:4 ), remote: true %></li>
         <li class="<%= params[:policy] == "5" ? "active-fon-fraction": "non-active-fon-fraction" %>"><%= link_to "Переважно голосує проти", people_detal_path(@mp.url_name, vote: "policy", policy:5 ), remote: true %></li>
         <li class="<%= params[:policy] == "6" ? "active-fon-fraction": "non-active-fon-fraction" %>"><%= link_to "Послідовно голосує проти", people_detal_path(@mp.url_name, vote: "policy", policy:6 ), remote: true %></li>
         <li class="<%= params[:policy] == "7" ? "active-fon-fraction": "non-active-fon-fraction" %>"><%= link_to "Максимально голосує проти", people_detal_path(@mp.url_name, vote: "policy", policy:7 ), remote: true %></li>
         <li class="<%= params[:policy] == "8" ? "active-fon-fraction": "non-active-fon-fraction" %>"><%= link_to "Ніколи не голосує", people_detal_path(@mp.url_name, vote: "policy", policy:8), remote: true %></li>
       </div>
      </ul>
      <select class="mobile_select_fraction d-block d-md-none" onchange="window.location.href=this.value;">
        <option <%= params[:policy] == "1"  ? 'selected="selected"' : "" %> value="<%=  people_detal_path(@mp.url_name, vote: "policy"  ) %>">Максимально голосує за</option>
        <option <%= params[:policy] == "2"  ? 'selected="selected"' : "" %> value="<%=  people_detal_path(@mp.url_name, vote: "policy", policy: 2 ) %>">Послідовно голосує за</option>
        <option <%= params[:policy] == "3"  ? 'selected="selected"' : "" %> value="<%=  people_detal_path(@mp.url_name, vote: "policy", policy: 3 ) %>">Переважно голосує за</option>
        <option <%= params[:policy] == "4"  ? 'selected="selected"' : "" %> value="<%=  people_detal_path(@mp.url_name, vote: "policy", policy: 4 ) %>">Суміш за та проти</option>
        <option <%= params[:policy] == "5"  ? 'selected="selected"' : "" %> value="<%=  people_detal_path(@mp.url_name, vote: "policy", policy: 5 ) %>">Переважно голосує проти</option>
        <option <%= params[:policy] == "6"  ? 'selected="selected"' : "" %> value="<%=  people_detal_path(@mp.url_name, vote: "policy", policy: 6 ) %>">Послідовно голосує проти</option>
        <option <%= params[:policy] == "7"  ? 'selected="selected"' : "" %> value="<%=  people_detal_path(@mp.url_name, vote: "policy", policy: 7 ) %>">Максимально голосує проти</option>
        <option <%= params[:policy] == "8"  ? 'selected="selected"' : "" %> value="<%=  people_detal_path(@mp.url_name, vote: "policy", policy: 8 ) %>">Ніколи не голосує</option>  
      </select>
      <div id="list_policy">
        <%= render "policy", policies: @policies %>
        <div class="index-pagination">

        </div>
      </div>
    </div>
<% else %>
    <% if @mp.mp_info.rebellions %>
      <p class="text-xs-center "><%= @mp.short_name %> голосував проти лінії фракції політичної партії
        "<%= @mp.faction %>" <%= @mp.mp_info.rebellions %> разів</p>
      <div id="list_vote">
        <%= render "voted", division: @division, mp: @mp %>
      </div>
    <% else %>
        <p class="text-xs-center "><%= @mp.short_name %> голосуваня проти лінії фракції "<%= @mp.faction %>" неможливо встановити</p>
        <div id="list_vote">
        </div>
    <% end %>
<% end %>

app/views/people/_friends.erb
<% friends.each_with_index do |f, i| %>
  <div class="row">
    <div class="col-3">
      <div class="progress">
        <div class="progress-bar-0<%= i %>-<%= friends.current_page %> progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="background-color: #FFDD2D">
          <%= fraction_to_percentage_display((f.count.to_f/mp.mp_info.votes_possible))%>
        </div>
      </div>
      <script type="text/javascript">
        //<![CDATA[
        $( document ).ready(function(){
          $(".progress-bar-0<%= i %>-<%=  friends.current_page %>").animate({
            width: "<%= fraction_to_percentage_display((f.count.to_f/mp.mp_info.votes_possible))%>"
          }, 2500);
        });
        //]]>
      </script>
       </div>
    <div class="col-3"><%= link_to f.mp2.full_name, show_people_path(f.mp2.url_name), :target => "_blank" %></div>
    <div class="col-3"><%= f.mp2.okrug %></div>
    <div class="col-3"><%= f.mp2.faction %></div>
  </div>
<% end %>
<div class="index-pagination">
  <% unless friends.last_page? or friends.blank? %>
      <%= link_to('<h4 class="text-uppercase text-center">Більше <i class="fa fa-arrow-circle-right" aria-hidden="true"></i></h4>'.html_safe, people_friends_path(params.merge(page: friends.current_page + 1)), remote: true, id: "load_more_link" ) %>
  <% end %>
</div>

app/views/people/_page.erb
<% mpsp.each_with_index do |m, i| %>
    <% if i % 2 == 0  %>
        <div class="row">
    <% end %>

    <div class="col-lg-6">
      <div class="col card card-person ">
        <%= link_to show_people_path(m.url_name), class: "" do %>
            <div class="row">
              <div class="col-3">
                <div class="img" style="background-image: url('/image/<%= m.deputy_id %>.png');"></div>
<!--                <img class="card-photo" src="/image/<%#= m.deputy_id %>.png" alt="<%#=  m.full_name  %>">-->
              </div>
              <div class="col-9">
                <p class="card-name"><%=  m.full_name  %></p>
                <p class="card-fraction">Фракція <%= member_role(m.faction, m.okrug).html_safe %></p>
                <p class="card-elected"><!--Обрано за списком партії  XXXX --></p>

                <div class="row check">
                  <div class="col-6 text-uppercase float-left">
                    <p class="checkin">присутність</p>
                    <p class="card-percent"><%= fraction_to_percentage_display(m.mp_info.attendance_fraction) %> засідань</p></div>
                  <div class="col-6 text-uppercase">
                    <p class="checkin">проти фракції</p>
                    <p class="card-percent"><%= fraction_to_percentage_display(m.mp_info.rebellions_fraction) %> голосувань</p>
                  </div>
                </div>
              </div>
            </div>
            </div>
        <% end %>
        </div>

    <% if i % 2== 1 %>
        </div>
    <% end %>

<% end %>
<div class="index-pagination">
<% unless mpsp.last_page? %>
    <%= link_to('<h4 class="text-uppercase text-center">Більше <i class="fa fa-arrow-circle-right" aria-hidden="true"></i></h4>'.html_safe,  people_next_path(params.merge(page: mpsp.current_page + 1 )), remote: true, :id=>'load_more_link')  %>
<% end %>
</div>

app/views/people/_show.erb
<div class="container">
  <%= render "header", mp: @mp %>
  <div id="det" class="container">
    <h2 class="center-justified text-xs-center text-uppercase background-line">Деталі голосувань</h2>

    <%= render "detal" %>
  </div>

</div>

app/views/people/_voted.erb
<div class="container">
    <div class="row">
        <% division.each do |d| %>
        <div class="col-12 col-md-6" style="margin-bottom: 25px">
            <%= link_to divisions_show_path(d.date, d.number), class: "" do %>
            <div class="col-12 pull-right card" style="padding: 25px 30px">
                <div class="row text-uppercase">
                    <p class="approve col-12"><i class="fa <%=  d.result == "Прийнято" ? "fa-check-circle" : "fa-times-circle"  %>" aria-hidden="true"></i> <%= d.result %></p>
                    <p class="card-date col-12"><%= d.date.strftime('%d.%m.%Y') %>, <%= Time.parse(d.clock_time).strftime('%H:%M') %> </p>
                </div>
                <div class="row card-text">
                    <p><%=  d.name  %></p>
                </div>
                <div class="row check">
                    <div class="col-6 col-md-4 text-uppercase float-left">
                        <p class="checkin">присутність</p>
                        <p class="card-percent"><%= fraction_to_percentage_display(d.division_info.attendance_division) %></p>
                    </div>
                    <div class="col-6 col-md-4 text-uppercase">
                        <p class="checkin">проти фракції</p>
                        <p class="card-percent"><%= d.division_info.rebellions %>  голосувань</p>
                    </div>

                    <div class="col-6 col-md-4 text-uppercase" style="color:#000;font-size: 8px;line-height: 18px;">
                      <%= result_voted(d.votes.find_mp(mp.deputy_id )) %>
                    </div>

                    <style>
                        

                    </style>
                </div>
            </div>
            <% end %>
        </div>
        <% end %>
    </div>
</div>
<div class="index-pagination">
  <% unless division.last_page? or division.blank? %>
      <%= link_to('<h4 class="text-uppercase text-center">Більше <i class="fa fa-arrow-circle-right fa-2x" aria-hidden="true"></i></h4>'.html_safe, people_divisions_path(params.merge(page: division.current_page + 1)), remote: true, id: "load_more_link" ) %>
  <% end %>
</div>

app/views/people/detal.js.erb
window.history.pushState("", "", "<%= show_people_path(params.merge(vote: params[:vote], action: nil, controller: nil, mp: nil)) %>");
$("#det").html("<%= escape_javascript(render(:partial => 'detal')) %>");

app/views/people/divisions.js.erb
$("#load_more_link").remove();
$("#list_vote").append("<%= escape_javascript(render(:partial => 'voted', :locals => {division: @division, mp: @mp })) %>");

app/views/people/friends.js.erb
$("#load_more_link").remove();
$("#list_vote").append("<%= escape_javascript(render(:partial => 'friends', :locals => {friends: @friends, mp: @mp })) %>");

app/views/people/index.html.erb
<% content_for :title, "Депутати — Як Голосує Твій Депутат?" %>

<div id="first-block" class="container">

    <div class="row justify-content-lg-center">
      <h1 class="col-lg-8 text-q text-uppercase">Депутати <%= Settings.name_rada %></h1>

      <div class="col-lg-8">
        <%= form_tag(search_mp_path, method: "get", class: "form-inline mt-2 mt-md-0", id: "search-main" ) do  %>
                              <span class="fa-stack">
                                <i class="fa fa-search fa-stack-1x fa-inverse" aria-hidden="true"></i>
                              </span>
            <%= text_field_tag(:mp, params[:mp] , class: "form-control mr-sm-2" , placeholder: "напр., " + placeholder , list: "members-datalist", autocomplete: "off" ) %>
            <i class="fa fa-chevron-down arrow-icon" aria-hidden="true"></i>
            <datalist id="members-datalist">
              <% @mp.each do |m| %>
                  <option value="<%= m.full_name %>"></option>
              <% end %>
            </datalist>
        <% end %>
       <script>  
        $(document).ready(function($) {
          $('#mp').change(function() {
            $('#search-main').submit();
          });
      });
      </script>
      </div>
    </div>
</div>

  <div id="profile" class="container">
    <%= render(:partial => 'index', :locals => {:mps => @mps}) %>
  </div>

<script>
    //added slider filter
    window.onload = function() {
        LoadPagePeople();
    };
</script>

app/views/people/index.js.erb
window.history.pushState("", "", "<%= request.fullpath  %>");
$("#profile").html("<%= escape_javascript(render(:partial => 'index', :locals => {:mps => @mps})) %>");
LoadPagePeople();

app/views/people/page.js.erb
$("#load_more_link").remove();
$("#list_mp").append("<%= escape_javascript(render(:partial => 'page', :locals => {:mpsp => @mps})) %>");

app/views/people/show.html.erb
<% content_for :title,  "#{ @mp.full_name } — Як Голосує Твій Депутат?" %>
<div id="profile">
  <%= render "show" %>
</div>

app/views/people/show.js.erb
window.history.pushState("", "", "<%= request.fullpath  %>");
$("#profile").html("<%= escape_javascript(render(:partial => 'show')) %>");