config/routes.rb
Rails.application.routes.draw do
  get 'policy_pepole/index'
  get 'person_policy/:mp/:id' => 'policy_pepole#index', as: :show_person_policy 
  get 'policy_divisions/:id/edit' => 'policy_divisions#edit', as: :edit_policy_division
  get 'policy_divisions/:date/:id' => 'policy_divisions#new', as: :new_policy_division
  get 'policy_divisions/:date/:id/policy' => 'policy_divisions#policy', as: :get_policy_division
  resources :policy_divisions
  get 'policies/policy', as: :policies_next
  get 'policies/history/:id' => 'policies#history', as: :history_policy
  resources :policies
  devise_for :users, controllers: { sessions: 'users/sessions', passwords: 'users/passwords', registrations: 'users/registrations', confirmations: 'users/confirmations'  }, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  devise_scope :user do
    get '/auth/new_reg', to: "users/registrations#new_reg"
    get '/auth/history', to: "users/registrations#history"
    get '/auth/histories/:user_id', to: "users/registrations#history", as: :user_history
  end
  get 'api/divisions'
  get 'api/division'
  get 'api/policies'
  get 'api/policy'
  get 'api/mp'
  get 'api/mps'

  get 'errors/not_found'

  get 'errors/unacceptable'

  get 'errors/internal_error'

  get 'sumisne-holosuvannia' => 'sumisne_holosuvannia#init', as: :sumisne_holosuvannia
  get 'sumisne-holosuvannia/api' => 'sumisne_holosuvannia#api', as: :sumisne_holosuvannia_api

  get 'help/faq'

  get 'help/data'

  get 'help/licencing'

  get 'divisions' => 'divisions#index', as: :divisions
  get 'divisions/page', as: :divisions_next
  get 'divisions/:date/:id' => 'divisions#show', as: :divisions_show

  get 'people' => 'people#index', as: :people
  get 'people/page', as: :people_next
  get 'people/:mp' => 'people#show', as: :show_people
  get 'people/:mp/divisions' => 'people#divisions', as: :people_divisions
  get 'people/:mp/friends' => 'people#friends', as: :people_friends
  get 'people/:mp/policy' => 'people#policy', as: :people_policy
  get 'people/detal/:mp' => 'people#detal', as: :people_detal

  get 'about' => 'about#index', as: :about
  get 'search_mp' => 'home#search_mp', as: :search_mp
  get 'search' => 'home#search', as: :search
  get 'home/index'
  get "/404", :to => "errors#not_found"
  get "/422", :to => "errors#unacceptable"
  get "/500", :to => "errors#internal_error"

   root 'home#index'

end

app/models/division.rb
class Division < ApplicationRecord
  #paginates_per 50
  has_many :votes, -> { order(:deputy_id => :asc) }
  has_many :mps, through: :votes
  has_one :division_info
  has_many :division_infos
  has_many :whips


  def find_mp(id)
    find_by(deputy_id: id )
  end
  def self.find_by_search_query(query)
    where("UPPER(name) like :query_name ", { query_name: "%#{query.upcase}%" })
  end
  def self.to_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |d|
        csv << d.attributes.values_at(*column_names)
      end
    end
  end
end

app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController
  def index
    @divisions = division()
    respond_to do |format|
      format.html
      format.js
    end
  end
  def page
    @divisions_page = division()

    respond_to do |format|
      format.js
    end
  end
  def division
    if params[:per].nil?
      params[:per] = 6
    end
    divisions = Division.includes(:division_info)
    unless params[:divisions].blank?
      divisions = divisions.find_by_search_query(params[:divisions])
      if params[:sort].nil?
        params[:sort] = "attendance"
      end
    else
      if params[:sort].nil?
        params[:sort] = "date"
      end
    end
    @divisions =
        case params[:sort]
          when "attendance"
            if params[:filter_min].nil? and params[:divisions].blank?
              params[:filter_min] = 30
            elsif params[:filter_min].nil? and params[:divisions]
              params[:filter_min] = 0
            end
            if params[:filter_max].nil? and params[:divisions].blank?
              params[:filter_max] = 90
            elsif params[:filter_max].nil? and params[:divisions]
              params[:filter_max] = 100
            end
            divi = divisions.to_a.find_all{|m| m.division_info.attendance_division.to_f >= params[:filter_min].to_f/100 and m.division_info.attendance_division.to_f <= params[:filter_max].to_f/100 }.sort_by{ |m| [-(m.division_info.attendance_division || -1), m.date, m.number ]}
            Kaminari.paginate_array(divi).page(params[:page]).per(params[:per])
          when "rebellions"
            if params[:filter_min].nil? and params[:divisions].blank?
              params[:filter_min] = 20
            elsif params[:filter_min].nil? and params[:divisions]
              params[:filter_min] = 0
            end
            if params[:filter_max].nil?
              params[:filter_max] = 90 and params[:divisions].blank?
            elsif params[:filter_max].nil? and params[:divisions]
              params[:filter_max] = 100
            end
            divi =divisions.to_a.find_all{|m| m.division_info.rebellions_fraction.to_f >= params[:filter_min].to_f/100 and m.division_info.rebellions_fraction.to_f <= params[:filter_max].to_f/100 }.sort_by{ |m| [-(m.division_info.rebellions_fraction || -1), m.date, m.number ]}
            Kaminari.paginate_array(divi).page(params[:page]).per(params[:per])
          else
            if (params[:min_date].nil? or params[:min_date].blank? or params[:max_date].nil? or params[:max_date].blank?) and (params[:last].nil? or params[:last].blank?)
              params[:last] = "3"
            end
            if params[:last] == "3"
               params[:min_date] = (Date.today() - 3.month).strftime('%d.%m.%Y')
               params[:max_date] = Date.today().strftime('%d.%m.%Y')
            elsif params[:last] == "1"
              min_date = Date.strptime((Division.order(date: :asc).pluck(:date).last.strftime('%m.%Y')), '%m.%Y')
              params[:min_date] = min_date.strftime('%d.%m.%Y')
              params[:max_date] = (min_date + 1.month - 1.day).strftime('%d.%m.%Y')
            end
            divisions.where("date >= ? AND date <= ?", Date.strptime(params[:min_date], '%d.%m.%Y'), Date.strptime(params[:max_date], '%d.%m.%Y')).order(date: :desc, number: :desc).page(params[:page]).per(params[:per])
        end
  end
  def show
    @division = Division.includes(:division_info).find_by(date: params[:date], number: params[:id])
    @whips = Whip.where(division_id: @division.id).order(:party)
    vote = Vote.includes(:mp, :division).where(division_id: @division.id).order('mps.faction')
    @voted = vote.to_a.map{|v| {name: v.mp.full_name, url: v.mp.url_name,  vote: v.vote, party: v.mp.faction } }.group_by{|f| f[:party]}
    respond_to do |format|
      format.html
      format.csv { send_data vote.to_div_csv , :filename =>  vote.first.division.name + '.csv' }
    end
  end
end

app/helpers/divisions_helper.rb
module DivisionsHelper
  def sort_division
    if params[:sort] == "subject"
      "Алфавітом"
    elsif params[:sort] == "rebellions"
      "Дотриманням фракційної дисципліни"
    elsif params[:sort] == "attendance"
      "Присутністю"
    else
      "Датою"
    end
  end
  def class_division(result)
    case result
      when "Прийнято"
        "passed"
      else
        "no_passed"
    end
  end
  def result_voted_mp(res)
    case res
      when "not_voted"
        "Не голосував"
      when "absent"
        "Відсутній"
      when "against"
        "Ні"
      when "aye"
        "Так"
      when "abstain"
        "Утримався"
    end
  end
end

app/views/divisions/_index.erb
<div class="list-filters clearfix">
  <ul class="sort-first text-uppercase d-none d-sm-none d-md-none d-lg-block">
    <li <%= params[:sort] == "date" ? "class=disabled": "" %> ><%= link_to "За Датою", params.merge(sort: :date, filter_min: nil, filter_max: nil), remote: true %></li>
    <li <%= params[:sort] == "attendance" ? "class=disabled": "" %> ><%= link_to "За Присутністю", params.merge(sort: :attendance, filter_min: nil, filter_max: nil, min_date:nil, max_date: nil, last: nil), remote: true %></li>
    <li <%= params[:sort] == "rebellions" ? "class=disabled": "" %> ><%= link_to "ЗА ФРАКЦІЙНОЮ ДИСЦИПЛІНОЮ", params.merge(sort: :rebellions, filter_min: nil, filter_max: nil, min_date:nil, max_date: nil, last: nil), remote: true %></li>
  </ul>
  <select class="mobile_select d-block d-md-none" onchange="window.location.href=this.value;">
      <option  <%= params[:sort]== "date" ? 'selected="selected"': ''%> value="<%=divisions_path(params.merge(sort: :date, filter_min: nil, filter_max: nil))%>">За Датою</option>
      <option <%= params[:sort]== "attendance" ? 'selected="selected"': ''%> value="<%=divisions_path(params.merge(sort: :attendance, filter_min: nil, filter_max: nil, min_date:nil, max_date: nil, last: nil))%>">За Присутністю</option>
      <option <%= params[:sort] == "rebellions" ? 'selected="selected"': ''%> value="<%=divisions_path(params.merge(sort: :rebellions, filter_min: nil, filter_max: nil, min_date:nil, max_date: nil, last: nil))%>">ЗА ФРАКЦІЙНОЮ ДИСЦИПЛІНОЮ</option>
  </select>


  <% if params[:sort] == "attendance" %>
      <div id="slider-range">
        <div id="custom-handle" class="ui-slider-handle"></div>
      </div>
  <% end %>

  <% if params[:sort] == "rebellions" %>
      <div id="slider-range">
        <div id="custom-handle" class="ui-slider-handle"></div>
      </div>
  <% end %>

  <% if params[:sort] == "date" %>
      <ul class="sort-fraction d-none d-sm-none d-md-none d-lg-block">
        <li <%= params[:last] == "3" ? 'class="active-fon-fraction"'.html_safe : ""  %>><%= link_to "За останні 3 місяця", params.merge(last: "3"), remote: true %></li>
        <li <%= params[:last] == "1" ? 'class="active-fon-fraction"'.html_safe : ""  %>><%= link_to "За останній пленарний місяць", params.merge(last: "1"), remote: true %></li>
      </ul>

    <div id="calendar" class="row text-xs-center text-uppercase">
      <div class="col-12 col-lg-4" style="margin:20px 0">
      <label for="from">за період з</label>
      <input type="text" id="from" name="from" value="<%= params[:min_date] %>">
        <i class="fa fa-chevron-down arrow-icon date-pointer" aria-hidden="true"></i>
      </div>
      <div class="col-12 col-lg-4" style="margin:20px 0">
      <label for="to">до</label>
      <input type="text" id="to" name="to" value="<%= params[:max_date] %>">
        <i class="fa fa-chevron-down arrow-icon date-pointer" aria-hidden="true"></i>
      </div>
    </div>
      <script>

          function AjaxGetDate (min_date, max_date) {
              $.ajax({
                  <% if params[:divisions].nil? or params[:divisions].blank?  %>
                  url: "/divisions?min_date=" + min_date + "&max_date=" + max_date + "",
                  <% else %>
                  url: "/divisions?min_date=" + min_date + "&max_date=" + max_date + "&divisions=<%= params[:divisions] %> ",
                  <% end %>
                  headers: {
                      Accept: "text/javascript, application/javascript, application/ecmascript, application/x-ecmascript",
                      "Content-Type": "text/javascript; charset=utf-8"
                  }
              });
          }
          $( "#calendar input[type='text']" ).change(function() {
              var min_date = $('#from').val(),
              max_date = $('#to').val();
              AjaxGetDate(min_date, max_date);
          });
          //    DatePiker
          $(function () {
              var dateFormat = 'dd.mm.yy',
                  from = $("#from")
                      .datepicker({
                          defaultDate: "+1w",
                          changeMonth: true,
                          numberOfMonths: 1,
                          regional: ["uk"]
                      })
                      .on("change", function () {
                          to.datepicker("option", "minDate", getDate(this));
                          var min_date = $('#from').val(),
                              max_date = $('#to').val();
                          AjaxGetDate(min_date, max_date);
                      }),
                  to = $("#to").datepicker({
                      defaultDate: "+1w",
                      changeMonth: true,
                      numberOfMonths: 1,
                      regional:  ["uk"]
                  })
                      .on("change", function () {
                          from.datepicker("option", "maxDate", getDate(this));
                          var min_date = $('#from').val(),
                              max_date = $('#to').val();
                          AjaxGetDate(min_date, max_date);
                      });

              function getDate(element) {
                  var date;
                  try {
                      date = $.datepicker.parseDate(dateFormat, element.value);
                  } catch (error) {
                      date = null;
                  }

                  return date;
              }
          });
      </script>
  <% end %>
  <div id="list_division">
    <%= render "voted", division: divisions  %>
  </div>

</div>
<script>
    window.onload = LoadPage;
        function LoadPage() {
        //slider range
        $(function () {
            $("#slider-range").slider({
                range: true,
                min: 0,
                max: 100,
                step: 10,
                values: [<%= params[:filter_min] %>, <%= params[:filter_max] %>],
                slide: function (event, ui) {
                    $.ajax({
                        <% if params[:divisions].nil? or params[:divisions].blank?  %>
                        url: "/divisions?filter_min=" + ui.values[0] + "&filter_max=" + ui.values[1] + "&sort=<%= params[:sort]  %>",
                        <% else %>
                        url: "/divisions?filter_min=" + ui.values[0] + "&filter_max=" + ui.values[1] + "&sort=<%= params[:sort]  %>&divisions=<%= params[:divisions] %>",
                        <% end %>
                        headers: {
                            Accept: "text/javascript, application/javascript, application/ecmascript, application/x-ecmascript",
                            "Content-Type": "text/javascript; charset=utf-8"
                        }
                    });
                }
            }).each(function () {

                // Add labels to slider whose values
                // are specified by min, max

                // Get the options for this slider (specified above)
                var opt = $(this).data().uiSlider.options;

                // Get the number of possible values
                var vals = opt.max - opt.min;

                // Position the labels
                for (var i = 0; i <= vals; i = i + opt.step) {

                    // Create a new element and position it with percentages
                    var el = $('<label></label>').css('left', (i) + '%');

                    // Add the element inside #slider
                    $("#slider-range").append(el);

                }
                $('#custom-handle').append($('<span class = "custom-handle"><%= params[:filter_min] %>%</span>'));
                $('span.ui-slider-handle').append($('<span class = "custom-handle"><%= params[:filter_max] %>%</span>'));
                ;

            });
        });

    }
</script>

app/views/divisions/_voted.erb
<div class="row">
    <div class="container">
      <div class="row">
        <% division.each do |d| %>
            <%= link_to divisions_show_path(d.date, d.number), class: "col-12 col-lg-6" do %>
                <div class="col pull-right card">
                  <div class="row">
                    <div class="col-3 text-uppercase">
                      <div class="col-12"><i class="fa <%=  d.result.gsub(/[[:space:]]/, '') == "Прийнято" ? "fa-check-circle" : "fa-times-circle"  %>" aria-hidden="true"></i></div>
                      <p class="approve"><%= d.result %></p>
                      <p class="card-date"><%= d.date.strftime('%d.%m.%Y') %>, <%= Time.parse(d.clock_time).strftime('%H:%M') %> </p>
                    </div>
                    <div class="col-9 card-text">
                      <p><%=  d.name  %></p>
                      <div class="row check">
                        <div class="col col-sm-5 text-uppercase float-left">
                          <p class="checkin">присутність</p>
                          <p class="card-percent"><%= fraction_to_percentage_display(d.division_info.attendance_division) %></p>
                        </div>
                        <div class="col col-sm-4 text-uppercase">
                          <p class="checkin">проти фракції</p>
                          <p class="card-percent"><%= d.division_info.rebellions %>  голосувань</p>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
            <% end %>
        <% end %>
      </div>

    </div>
</div>
<div class="index-pagination">

  <% unless division.last_page? or division.blank? %>
      <%= link_to('<h4 class="text-uppercase text-center">Більше <i class="fa fa-arrow-circle-right" aria-hidden="true"></i></h4>'.html_safe, divisions_next_path(params.merge(page: division.current_page + 1)), remote: true, id: "load_more_link" ) %>
  <% end %>
</div>

app/views/divisions/index.html.erb
<% content_for :title, "Голосування — Як Голосує Твій Депутат?" %>

<div id="first-block" class="container people">
  <h1 class="text-uppercase center-justified text-xs-center">голосування <%= Settings.name_rada %></h1>
  <div class="row">
    <%= form_tag(divisions_path, method: "get", class: "col-8 form-inline mt-2 mt-md-0 push-2", id: "search-main", remote: true  ) do  %>
                          <span class="fa-stack">
                            <i class="fa fa-search fa-stack-1x fa-inverse" aria-hidden="true"></i>
                          </span>
        <%= text_field_tag(:divisions, params[:divisions] , class: "form-control mr-sm-2" , placeholder: "Шукати по заголовку" ) %>
        <!--<i class="fa fa-chevron-down arrow-icon" aria-hidden="true"></i>-->
    <% end %>
  </div>
  <div id="division">
    <%= render(:partial => 'index', :locals => {:divisions => @divisions}) %>
  </div>
</div>

app/views/divisions/index.js.erb
window.history.pushState("", "", "<%= request.fullpath  %>");
$("#division").html("<%= escape_javascript(render(:partial => 'index', :locals => {:divisions => @divisions})) %>");
LoadPage();

app/views/divisions/page.js.erb
$("#load_more_link").remove();
$("#list_division").append("<%= escape_javascript(render(:partial => 'voted', :locals => {:division => @divisions_page})) %>");

app/views/divisions/show.html.erb
<% content_for :title, "Голосування — Як Голосує Твій Депутат?" %>

<div id="divisionshow" class="container">
    <h1 class="text-uppercase center-justified text-xs-center">Голосування <%= Settings.name_rada %></h1>

    <div class="row">
        <div class="col">
            <ul class="social text-uppercase">
                <li>
                    <!--<span class="fa-stack ">-->
                      <!--<i class="fa fa-square-o fa-stack-2x"></i>-->
                      <!--<i class="fa  fa-download  fa-stack-1x"></i>-->
                    <!--</span>-->
                    <!--<a href="" >текст рішення</a>-->
                </li>
            </ul>
        </div>
        <ul class="social col-sm-12 col-md-4 pull-right text-uppercase">
            <li>
              <%= link_to divisions_show_path(@division.date, @division.number, format: :csv) do %>
                    <span class="fa-stack ">
                      <i class="fa fa-square-o fa-stack-2x"></i>
                      <i class="fa  fa-download  fa-stack-1x"></i>
                    </span>csv
              <% end %>
            </li>

            <li>
              <span class="fa-stack ">
                      <i class="fa fa-square-o fa-stack-2x"></i>
                      <i class="fa  fa-download  fa-stack-1x"></i>
              </span>
              <%= link_to "Пов’язані політики", new_policy_division_path(@division.date, @division.number) %>
            </li>

            <li>
                    <span class="fa-stack ">
                    <i class="fa  fa-share-alt  fa-stack-1x"></i>
                        </span>
              <a href="https://www.facebook.com/sharer/sharer.php?u=<%= request.protocol  + request.host +  request.fullpath %>" target="_blank">поширити</a>
            </li>
        </ul>
    </div>

    <div class="row">
        <div class="container">
            <div class="col-12 pull-right card">
                <div class="row">
                    <div class="col text-uppercase text-xs-center">
                        <div class="approve col-12">
                            <i class="fa <%=  @division.result.gsub(/[[:space:]]/, '') == "Прийнято" ? "fa-check-circle" : "fa-times-circle"  %>" aria-hidden="true"></i>
                            <p class="approve"><%= @division.result %></p>
                        </div>
                        <p class="card-date"><%= @division.date.strftime('%d.%m.%Y') %>, <%= Time.parse(@division.clock_time).strftime('%H:%M') %>  </p>
                    </div>
                    <div class="col-10 card-text">

                        <p><%=  @division.name  %></p>
                    </div>
                </div>
            </div>
        </div>
    </div>

<div class="container-fluid">
      <h2 class="text-uppercase center-justified ">Статистика голосування </h2>
      <% if @division.division_info.rebellions > 0 %>
        <p>Відбулося <span class="rebel"><%= @division.division_info.rebellions %> голосування</span> проти лінії фракції.</p>
      <% else %>
        <p>Ніхто не голосував проти лінії фракції</p>
      <% end %>

    <% @whips.each_with_index  do |w, i| %>
      <div id="accordion-<%= i %>" class="row panel-group">
          <div class="col-12 panel panel-default">
              <div class="panel-heading">
                  <a data-toggle="collapse" data-parent="#accordion-<%= i %>" href="#detail-<%= i %>" class="collapsed" aria-expanded="false">
                      <h3 class="panel-title text-uppercase">
                      <%= w.party %>
                      </h3>
                      <div class="row golos">
                          <div class="col text-uppercase <%= w.whip_guess != "aye" and w.aye_votes > 0 ? "rebel" : "normal" %>">за <span><%= w.aye_votes %></span></div>
                          <div class="col text-uppercase <%= w.whip_guess != "against" and w.against > 0 ? "rebel" : "normal" %>">проти <span><%= w.against %></span></div>
                          <div class="col text-uppercase <%= w.whip_guess != "abstain" and  w.abstain > 0 ? "rebel" : "normal" %>">утримався <span><%= w.abstain %></span></div>
                          <div class="col text-uppercase <%= w.whip_guess != "not_voted" and  w.no_votes > 0 ? "rebel" : "normal" %>">не голосував <span><%= w.no_votes %></span></div>
                          <div class="col-4 text-uppercase">
                              <div class="row">
                                  присутність
                                  <div class="progress col-8">
                                      <div class="progress-bar-<%= i %> progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" >
                                          <%= fraction_to_percentage_display((w.aye_votes + w.against + w.abstain + w.no_votes).to_f/(w.aye_votes + w.against + w.abstain + w.no_votes + w.absent))%>
                                      </div>
                                  </div>
                                  <i class="chevron fa fa-fw" ></i>
                              </div>
                              <script type="text/javascript">
                                  //<![CDATA[
                                  $( document ).ready(function(){
                                      $(".progress-bar-<%= i %> ").animate({
                                          width: "<%= fraction_to_percentage_display((w.aye_votes + w.against + w.abstain + w.no_votes).to_f/(w.aye_votes + w.against + w.abstain + w.no_votes + w.absent))%>"
                                      }, 2500);
                                  });
                                  //]]>
                              </script>
                          </div>
                      </div>
                  </a>
              </div>

              <div id="detail-<%= i %>" class="panel-collapse detail collapse container" aria-expanded="false" >
                  <div class="row">
                      <div class="col-4 text-uppercase">
                          результати голосування
                      </div>

                      <div class="col-8">
                          <% @voted[w.party].each do |v| %>
                          <div  class="member-row member-row-<%= i %> party-member-row row" >

                              <div class="panel-body col-8">
                                  <%= link_to v[:name], show_people_path(v[:url]), target: "_blank" %>
                              </div>

                              <div class="col-4 text-uppercase <%=  w.whip_guess == v[:vote] or  v[:vote] =="absent" ? "": "rebel"   %>"><%= result_voted_mp(v[:vote]) %></div>

                          </div>
                          <% end %>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    <% end %>

</div>

<div class="container-fluid all">

        <h3 class="panel-title text-uppercase">Всього</h3>

    <div class="row golos detail">
        <div class="col text-uppercase ">Так  <span ><%=  @division.division_info.aye_votes %> </span></div>
        <div class="col text-uppercase ">Ні <span>  <%=  @division.division_info.against %> </span></div>
        <div class="col text-uppercase  ">Утрималися <span><%=  @division.division_info.abstain %> </span></div>
        <div class="col text-uppercase ">Не голосували <span><%=  @division.division_info.no_votes %> </span></div>
        <div class="col-4 text-uppercase">
            <div class="row">
                присутність
                <div class="progress col-8">
                    <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">
                        <%= fraction_to_percentage_display(@division.division_info.attendance_division) %>
                    </div>
                </div>
                <script type="text/javascript">
                    //<![CDATA[
                    $( document ).ready(function(){
                        $(".all .progress-bar").animate({
                            width: "<%= fraction_to_percentage_display(@division.division_info.attendance_division) %>"
                        }, 2500);
                    });
                    //]]>
                </script>
            </div>

        </div>
    </div>
</div>
</div>