config/routes.rb
Rails.application.routes.draw do
  get 'policy_pepole/index'
  get 'person_policy/:mp/:id' => 'policy_pepole#index', as: :show_person_policy 
  get 'policy_divisions/:id/edit' => 'policy_divisions#edit', as: :edit_policy_division
  get 'policy_divisions/:date/:id' => 'policy_divisions#new', as: :new_policy_division
  get 'policy_divisions/:date/:id/policy' => 'policy_divisions#policy', as: :get_policy_division
  resources :policy_divisions
  get 'policies/policy', as: :policies_next
  get 'policies/history/:id' => 'policies#history', as: :history_policy
  resources :policies
  devise_for :users, controllers: { sessions: 'users/sessions', passwords: 'users/passwords', registrations: 'users/registrations', confirmations: 'users/confirmations'  }, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  devise_scope :user do
    get '/auth/new_reg', to: "users/registrations#new_reg"
    get '/auth/history', to: "users/registrations#history"
    get '/auth/histories/:user_id', to: "users/registrations#history", as: :user_history
  end
  get 'api/divisions'
  get 'api/division'
  get 'api/policies'
  get 'api/policy'
  get 'api/mp'
  get 'api/mps'

  get 'errors/not_found'

  get 'errors/unacceptable'

  get 'errors/internal_error'

  get 'sumisne-holosuvannia' => 'sumisne_holosuvannia#init', as: :sumisne_holosuvannia
  get 'sumisne-holosuvannia/api' => 'sumisne_holosuvannia#api', as: :sumisne_holosuvannia_api

  get 'help/faq'

  get 'help/data'

  get 'help/licencing'

  get 'divisions' => 'divisions#index', as: :divisions
  get 'divisions/page', as: :divisions_next
  get 'divisions/:date/:id' => 'divisions#show', as: :divisions_show

  get 'people' => 'people#index', as: :people
  get 'people/page', as: :people_next
  get 'people/:mp' => 'people#show', as: :show_people
  get 'people/:mp/divisions' => 'people#divisions', as: :people_divisions
  get 'people/:mp/friends' => 'people#friends', as: :people_friends
  get 'people/:mp/policy' => 'people#policy', as: :people_policy
  get 'people/detal/:mp' => 'people#detal', as: :people_detal

  get 'about' => 'about#index', as: :about
  get 'search_mp' => 'home#search_mp', as: :search_mp
  get 'search' => 'home#search', as: :search
  get 'home/index'
  get "/404", :to => "errors#not_found"
  get "/422", :to => "errors#unacceptable"
  get "/500", :to => "errors#internal_error"

   root 'home#index'

end

app/views/layouts/_history.erb
<% @history.each do |r|  %>
    <div class="col-12">
      <% if r.item_type == "PolicyDivision" %>
          <p>В політиці: <strong><%= link_to policy_name(r.policy_id), policy_path(r.policy_id) %></strong></p>
          <% if r.event == "create" %>
              <p>Додано голосування: "<%= link_to divisions_name(r.division_id), divisions_show_path(div_path(r.division_id)) %>"</p>
              <p>Голосування щодо політики визначене як “<%=  display_support(r.changeset["support"].second)  %>”.</p>
          <% elsif  r.event == "update"  %>
              <p>Оновлено голосування: "<%= link_to divisions_name(r.division_id), divisions_show_path(div_path(r.division_id)) %>"</p>
              <p>Голосування щодо політики визначене з “<%=  display_support(r.changeset["support"].first)  %>” на “<%=  display_support(r.changeset["support"].second)  %>”.</p>
          <% else %>
              <p>Видалено голосування: "<%= link_to divisions_name(r.division_id), divisions_show_path(div_path(r.division_id)) %>"</p>
              <p>Голосування щодо політики визначалось як “<%=  display_support(most_recent_version(r.item_type, r.item_id ).changeset["support"].second)  %>”.</p>
          <% end %>
      <% else %>
          <% if r.event == "create" %>
              <p>Створено проект політики <strong>"<%=  link_to r.changeset["name"].second,  policy_path(r.policy_id) %>"</strong> з описом “<%= r.changeset["description"].second %>”.</p>
          <% else %>
              <p>Оновлено <strong>"<%= link_to policy_name(r.item_id), policy_path(r.policy_id) %>"</strong> </p>
              <% if r.changeset["name"] %>
                  <p>Назву змінено з <strong>"<%=  link_to r.changeset["name"].first, policy_path(r.policy_id) %>"</strong> на <strong>"<%= link_to r.changeset["name"].second, policy_path(r.policy_id) %>"</strong></p>
              <% end %>
              <% if r.changeset["description"] %>
                  <p>Опис змінено з <strong>"<%= r.changeset["description"].first %>"</strong> на <strong>"<%= r.changeset["description"].second %>"</strong></p>
              <% end %>
              <% if r.changeset["provisional"] %>
                  <p>Змінено статус на <%= r.changeset["provisional"].second ? "не проект" : "проект" %>.</p>
              <% end %>
          <% end %>
      <% end %>
      <% if controller.controller_path=="policies" %>
          <p><%= link_to User.find(r.whodunnit).user_name, user_history_path(r.whodunnit) %>, <%= r.created_at.strftime('%d.%m.%Y / %H:%M') %></p>
      <% else %>
        <p><%= r.created_at.strftime('%d.%m.%Y / %H:%M') %></p>
      <% end %>
      <hr>
    </div>

<% end %>
<div class="index-pagination">
  <% unless @history.last_page? or @history.blank? %>
      <% if controller.controller_path=="policies" %>
        <%= link_to('<h4 class="text-uppercase text-center">Більше <i class="fa fa-arrow-circle-right fa-2x" aria-hidden="true"></i></h4>'.html_safe, history_policy_path(params.merge(page: @history.current_page + 1)), remote: true, id: "load_more_link" ) %>
      <% else %>
          <%= link_to('<h4 class="text-uppercase text-center">Більше <i class="fa fa-arrow-circle-right fa-2x" aria-hidden="true"></i></h4>'.html_safe, auth_history_path(params.merge(page: @history.current_page + 1)), remote: true, id: "load_more_link" ) %>
<% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title><%= yield(:title) %></title>
  <base href="" />
  <meta name="description" content="" />
  <meta name="keywords" content= "" />
  <meta property="og:title" content="<%= yield(:title) %>" />
  <meta property="og:type" content="website" />
  <meta property="og:url" content="http://" />
  <meta property="og:image" content="http://logo" />
  <meta property="og:site_name" content="" />

  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <!-- Bootstrap CSS -->
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">


  <%= stylesheet_link_tag 'bootstrap', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'style', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'media', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag body_class, media: 'all', 'data-turbolinks-track' => true  %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.3/css/bootstrap-select.min.css">
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
   <script async src="https://www.googletagmanager.com/gtag/js?id=<%= Settings.gtag %>"></script>
<script>
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());

gtag('config', '<%= Settings.gtag %>');
</script>
  <%= csrf_meta_tags %>
</head>
<body id = "<%=  body_class %>" >
<!--<span id="forkongithub"><a href="">Бета версія: Політики,Кабінет,Історія</a></span>-->
<% if notice or alert %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <p><%= notice %>  <%= alert %></p>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
    <% unless request.path == "/500" %>
    <header class="container-fluid">
      <nav class="navbar navbar-toggleable-md navbar-light">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <% if controller.controller_path == "home" %>
          <%= link_to "<p><i class='fa fa-circle fa-stack-1x'></i><span class='first-word'>#{Settings.name_site}</span>.Rada4You.org</p>".html_safe, root_path, class: "navbar-brand text-uppercase logo" %>
        <% end %>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to "Депутати", people_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Голосування", divisions_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Політики", policies_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Сумісні голосування", sumisne_holosuvannia_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Про проект", about_path, class: "nav-link"  %>
            </li>
          </ul>

          <ul class="navbar-nav">
            <li class="nav-item d-none d-sm-none d-md-none d-lg-block">
              <div class="button-search">
                <i class="fa fa-search" aria-hidden="true"></i>
                <input type="button" value="Пошук" class="btn btn-primary" data-toggle="modal" data-target="#ModalSearch" >
              </div>
            </li>
            <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to current_user.user_name, edit_user_registration_path, class: "nav-link"  %>
                </li>
            <% else %>
             <li class="nav-item reg-link">
                <%= link_to "Вхід",  new_user_session_path, class: "nav-link"  %>
              </li>
                <li class="nav-item span d-none d-lg-block" style="padding-left: 0; padding-right: 0"><span>/</span></li>
              <li class="nav-item reg-link">
                <%= link_to "Реєстрація", new_user_registration_path, class: "nav-link reg-link"  %>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
      <% if controller.controller_path == "home" %>
        <div id="info" class="container">
            <div class="row justify-content-end">
                <div class="col-lg-3 col-6 update-data">
                   <span class="fa-stack">
                              <i class="fa fa-circle fa-stack-2x"></i>
                              <i class="fa fa-clock-o fa-stack-1x fa-inverse" aria-hidden="true"></i>
                          </span>
                    <p class="text-uppercase">Оновлення даних</p>
                    <p><%= last_update_rada %></p>
                </div>
                <div class="col-lg-3 col-6 rada-date">
                    <span class="fa-stack">
                              <i class="fa fa-circle fa-stack-2x"></i>
                              <i class="fa fa-clock-o fa-stack-1x fa-inverse" aria-hidden="true"></i>
                          </span>
                    <p class="text-uppercase">Засідання міськради</p>
                    <p><%= last_sessions_rada() %></p>
                </div>
            </div>
        </div>
        <div style="clear: both;"></div>
      <% end %>

      <% if controller.controller_path != "home" %>
            </header>
          <div id="info" class="container">
              <%= link_to "<p><i class='fa fa-circle fa-stack-1x'></i><span class='first-word'>#{Settings.name_site}</span>.Rada4You.org</p>".html_safe, root_path, class: "col-4 navbar-brand text-uppercase logo", id: "logo" %>

              <div class="row justify-content-end">
              <% if controller.controller_path != "errors" %>
              <% unless controller.controller_path == "policy_pepole" %>
              <div class="col-lg-3 col-6 update-data">
                          <span class="fa-stack">
                              <i class="fa fa-clock-o fa-stack-1x fa-inverse" aria-hidden="true"></i>
                          </span>
                <p class="text-uppercase">Оновлення даних</p>
                <p><%= last_update_rada %></p>
              </div>
              <%end%>
              <div class="col-lg-3 col-6 rada-date">
                          <span class="fa-stack">
                              <i class="fa fa-clock-o fa-stack-1x fa-inverse" aria-hidden="true"></i>
                          </span>
                <p class="text-uppercase">Засідання міськради</p>
                <p><%= last_sessions_rada() %></p>
              </div>
              <% end %>
            </div>
          </div>
      <% end %>
    <% end %>

  <%= yield %>
<% unless request.path == "/500" %>
<footer>
  <div class="container">
    <div class="col-12"><p class="text-center title">Проект Громадянської мережі <%= link_to "ОПОРА", "http://oporaua.org", target: "_blank"  %></p></div>
    <div class="row">
      <div class="col-12 col-md-4 col-lg-4 col-xs-4"><span>Усі дані та програмне забезпечення надаються з відкритим вихідним кодом та є вільними для поширення </span></div>
      <div class="col-12 col-md-4 col-lg-4 col-xs-4">
                    <span class="fa-stack fa-2x">
                        <a href="https://facebook.com/DorogiDeputaty"><i class="fa fa-circle-thin fa-stack-2x"></i>
                          <i class="fa fa-facebook fa-stack-1x fa-inverse" aria-hidden="true"></i></a>
                    </span>
        <span class="fa-stack fa-2x">
                        <a href="https://twitter.com/rada4you"><i class="fa fa-circle-thin fa-stack-2x"></i>
                          <i class="fa fa-twitter fa-stack-1x fa-inverse" aria-hidden="true"></i></a>
                    </span>
        <span class="fa-stack fa-2x">
                        <a href="mailto:rada4you@opora.org.ua"><i class="fa fa-circle-thin fa-stack-2x"></i>
                          <i class="fa fa-envelope fa-stack-1x fa-inverse" aria-hidden="true"></i></a>
                    </span>

      </div>
      <div class="col-12 col-md-4 col-lg-4 col-xs-4 text-uppercase">
        <p><%= link_to "API", help_data_path, rel: "nofollow"  %></p>
        <p><%= link_to "Поширені питання/FAQ", "https://rada4you.org/help/faq", rel: "nofollow" %></p>
        <p><%= link_to "Мапа сервісів", "https://rada4you.org/map", rel: "nofollow" %></p>

      </div>
    </div>
  </div>

</footer>
<% end %>
    <!-- Modal search -->
    <div id="ModalSearch" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">
                      <%= link_to "<p><i class='fa fa-circle fa-stack-1x'></i><span class='first-word'>#{Settings.name_site}</span>.Rada4You.org</p>".html_safe, root_path, class: "col navbar-brand text-uppercase logo" %>
                    </h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <span>Пошук по сайту</span>
                  <%= form_tag(search_path, method: "get", remote: true ) do  %>
                      <%= text_field_tag(:query, params[:query], placeholder: "Уведіть пошуковий запит" ) %>
                  <% end %>
                  <div id="search"></div>
                </div>
                
            </div>
        </div>
    </div>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.3/js/bootstrap-select.min.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<%= javascript_include_tag 'ukr_datepiker', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'html2canvas', 'data-turbolinks-track' => true %>
</body>
</html>