config/routes.rb
Rails.application.routes.draw do
  get 'policy_pepole/index'
  get 'person_policy/:mp/:id' => 'policy_pepole#index', as: :show_person_policy 
  get 'policy_divisions/:id/edit' => 'policy_divisions#edit', as: :edit_policy_division
  get 'policy_divisions/:date/:id' => 'policy_divisions#new', as: :new_policy_division
  get 'policy_divisions/:date/:id/policy' => 'policy_divisions#policy', as: :get_policy_division
  resources :policy_divisions
  get 'policies/policy', as: :policies_next
  get 'policies/history/:id' => 'policies#history', as: :history_policy
  resources :policies
  devise_for :users, controllers: { sessions: 'users/sessions', passwords: 'users/passwords', registrations: 'users/registrations', confirmations: 'users/confirmations'  }, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  devise_scope :user do
    get '/auth/new_reg', to: "users/registrations#new_reg"
    get '/auth/history', to: "users/registrations#history"
    get '/auth/histories/:user_id', to: "users/registrations#history", as: :user_history
  end
  get 'api/divisions'
  get 'api/division'
  get 'api/policies'
  get 'api/policy'
  get 'api/mp'
  get 'api/mps'

  get 'errors/not_found'

  get 'errors/unacceptable'

  get 'errors/internal_error'

  get 'sumisne-holosuvannia' => 'sumisne_holosuvannia#init', as: :sumisne_holosuvannia
  get 'sumisne-holosuvannia/api' => 'sumisne_holosuvannia#api', as: :sumisne_holosuvannia_api

  get 'help/faq'

  get 'help/data'

  get 'help/licencing'

  get 'divisions' => 'divisions#index', as: :divisions
  get 'divisions/page', as: :divisions_next
  get 'divisions/:date/:id' => 'divisions#show', as: :divisions_show

  get 'people' => 'people#index', as: :people
  get 'people/page', as: :people_next
  get 'people/:mp' => 'people#show', as: :show_people
  get 'people/:mp/divisions' => 'people#divisions', as: :people_divisions
  get 'people/:mp/friends' => 'people#friends', as: :people_friends
  get 'people/:mp/policy' => 'people#policy', as: :people_policy
  get 'people/detal/:mp' => 'people#detal', as: :people_detal

  get 'about' => 'about#index', as: :about
  get 'search_mp' => 'home#search_mp', as: :search_mp
  get 'search' => 'home#search', as: :search
  get 'home/index'
  get "/404", :to => "errors#not_found"
  get "/422", :to => "errors#unacceptable"
  get "/500", :to => "errors#internal_error"

   root 'home#index'

end

app/models/policy.rb
class Policy < ApplicationRecord
  has_many :policy_divisions
  has_many :policy_person_distances

  validates :name, presence: true
  validates :description, presence: true
  has_paper_trail(meta: {policy_id: :id})
  scope :very_strongly_for,     -> { where("policy_person_distances.distance >= ? AND policy_person_distances.distance < ?", 0.00, 0.05) }
  scope :strongly_for,          -> { where("policy_person_distances.distance >= ? AND policy_person_distances.distance < ?", 0.05, 0.15) }
  scope :moderately_for,        -> { where("policy_person_distances.distance >= ? AND policy_person_distances.distance < ?", 0.15, 0.40) }
  scope :for_and_against,       -> { where("policy_person_distances.distance >= ? AND policy_person_distances.distance < ?", 0.40, 0.60).where("( same + same_strong + diff + diff_strong ) > 0") }
  scope :moderately_against,    -> { where("policy_person_distances.distance >= ? AND policy_person_distances.distance < ?", 0.60, 0.85) }
  scope :strongly_against,      -> { where("policy_person_distances.distance >= ? AND policy_person_distances.distance < ?", 0.85, 0.95) }
  scope :very_strongly_against, -> { where("policy_person_distances.distance >= ? AND policy_person_distances.distance < ?", 0.95, 1.0) }
  scope :never_voted,           -> { where("same = 0 and same_strong = 0 and diff = 0 and diff_strong = 0") }

  def self.filter_polices(param)
    if param =="1"
      very_strongly_for
    elsif param =="2"
      strongly_for
    elsif  param =="3"
      moderately_for
    elsif  param =="4"
      for_and_against
    elsif  param =="5"
      moderately_against
    elsif param =="6"
      strongly_against
    elsif param =="7"
      very_strongly_against
    elsif param =="8"
      never_voted
    end
  end

  def self.find_by_search_query(query)
    where("UPPER(name) like :query_name ", { query_name: "%#{query.upcase}%" })
  end
  def self.to_csv
    CSV.generate do |csv|
      csv << ['id', 'name', 'description', 'provisional']
      all.each do |mp|
        csv << [mp.id, mp.name, mp.description, mp.provisional]
      end
    end
  end
end

app/controllers/policies_controller.rb
class PoliciesController < ApplicationController
  before_action :set_policy, only: [:edit, :update, :destroy]
  before_action :set_policy_with_mps, only: [:show]
  before_action :authenticate_user!, only: [ :new, :edit, :update, :destroy, :create]
  before_action :set_paper_trail_whodunnit

  # GET /policies
  # GET /policies.json
  def index
    @policies =  policies()
  end
  def policy
    @policies = policies()
    respond_to do |format|
      format.js
    end
  end
  # GET /policies/1
  # GET /policies/1.json
  def show
    if params[:history] == '1'
      history()
    end
    
  end
  def detal

  end

  # GET /policies/new
  def new
    @policy = Policy.new
    @policy.provisional = false
  end

  # GET /policies/1/edit
  def edit
  end

  # POST /policies
  # POST /policies.json
  def create
    @policy = Policy.new(policy_params)
    @policy.provisional = false
    respond_to do |format|
      if @policy.save
        format.html { redirect_to @policy, notice: ' Політика була успішно створена.' }
        format.json { render :show, status: :created, location: @policy }
      else
        format.html { render :new }
        format.json { render json: @policy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /policies/1
  # PATCH/PUT /policies/1.json
  def update
    respond_to do |format|
      @policy.provisional = provisional? ? false : true
      if @policy.update(policy_params)

        format.html { redirect_to @policy, notice: 'Політика була успішно оновлена' }
        format.json { render :show, status: :ok, location: @policy }
      else
        format.html { render :edit }
        format.json { render json: @policy.errors, status: :unprocessable_entity }
      end
    end
  end

  def history
    @history = PaperTrail::Version.where(policy_id: params[:id]).order(created_at: :desc ).page(params[:page]).per(4)
  end

  # DELETE /policies/1
  # DELETE /policies/1.json
  def destroy
    #@policy.destroy
    # respond_to do |format|
    #   format.html { redirect_to policies_url, notice: 'Policy was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
  end

  private
  def provisional?
    params[:commit] == "Зберегти проект політики"
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_policy
      @policy = Policy.includes(:policy_divisions).find(params[:id])
    end

    def set_policy_with_mps
      @policy = Policy.includes(:policy_divisions).find(params[:id])
      @policy_level_up = []
      (1..8).each do |l|
        if  @policy.policy_person_distances.filter_polices(l.to_s).count > 0
          @policy_level_up << l
        end
      end
      if params[:policy].nil?
        params[:policy] = @policy_level_up.first.to_s
      end
      if !@policy.policy_person_distances.blank?
        @polisy_mp = @policy.policy_person_distances.includes(:mp).filter_polices(params[:policy]).where(mps: {end_date: "9999-12-31"})
      end  
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def policy_params
      params.require(:policy).permit(:name, :description)
    end

    def policies

      unless params[:policies].blank?
        policies =  Policy.find_by_search_query(params[:policies])
      else
        if params[:filter].blank?
          policies = Policy.where(provisional: true)
        else
          policies = Policy.where(provisional: false)
        end
      end
      return policies.page(params[:page]).per(8)
    end
end

app/views/policies/_edit.erb
<div class="list-filters clearfix">
  <ul class="sort-first text-uppercase d-none d-sm-none d-md-none d-lg-block">
    <li <%= params[:sort].nil? ? "class=disabled": "" %> ><%= link_to "Опис політики", params.merge(sort: nil), remote: true %></li>
    <li <%= params[:sort] == "vote" ? "class=disabled": "" %> ><%= link_to "Пов’язані голосування (" + @policy.policy_divisions.size.to_s  + ")", params.merge(sort: :vote), remote: true %></li>
  </ul>
   <select class="mobile_select d-block d-md-none" onchange="window.location.href=this.value;">
      <option value="<%= edit_policy_path(@policy.id, sort: nil )%>">Опис політики</option>
      <option <%= params[:sort] == "vote" ? 'selected="selected"': ''%> value="<%=edit_policy_path(@policy.id, sort: :vote)%>">Пов’язані голосування ( <%= @policy.policy_divisions.size %> )</option>
    </select>
</div>
<% if  params[:sort].nil?  %>
    <%= render 'form', policy: @policy %>
<% else %>
    <div class="row" style="margin-bottom: 40px">
      <div class="col col-1"></div>
      <div class="col col-9">
        <p class="text-justifyr">Аби додати голосування до політики, на сторінці кожного голосування є відповідна опція. Якщо ти ще не редагував Політики, будь ласка, прочитай
          <a href="">Що таке Політики та як це працює?</a>.</p>
      </div>

    </div>
    <%= render "voted", division: @policy.policy_divisions %>
<% end %>

app/views/policies/_form.html.erb
<%= form_with(model: policy, local: true) do |form| %>
  <% if policy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(policy.errors.count, "error") %> prohibited this policy from being saved:</h2>

      <ul>
      <% policy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <strong>Якщо ти за</strong>
  <div class="field">
    <%  if controller.action_name == "new"  %>
    <%= form.label :name, "Заверши речення, надавши короткий, конкретний опис" %> <br>
     <% end %>
    <%= form.text_field :name, id: :policy_name, placeholder: "напр., За реформування системи охорони дитинства" %>
  </div>
    <strong>Ти віриш, що</strong>
    <div class="field">
      <%  if controller.action_name == "new"  %>
      <%= form.label :description, "Опиши переконання, яке має депутат, який підтримує Політику" %> <br>
          <% end %>
      <%= form.text_area :description, id: :description, placeholder: "напр., міська рада повинна адаптувати до нових реалій застарілу і неповоротку систему охорони дитинства, що мала б ефективно вирішувати питання сирітства та соціального захисту тощо" %>
    </div>
    <%  if controller.action_name == "new"  %>
    <div>
      <p>Після того, як політика створена, ти зможеш підв'язувати до неї голосування і бачити, як ті депутати, які
        підтримують таку політику, могли голосувати. Rada4you порівнює справжнє голосування депутатів з твоїм вибором і
        вираховує бали щодо підтримки чи непідтримки політики.</p>

      <a href="https://rada4you.org/help/faq#policies" target="_blank">Дізнайся більше про те, як формуються Політики</a>


      <p>Пам'ятай, що всі політики є публічними. Це ресурс, який можна редагувати та оновлювати будь-кому (як
        Вікіпедія)</p>
      <ul>
        <li>Приватність — Створивши політику, вона буде закріплена за тобою <%= current_user.user_name %> як за автором</li>
        <li>Ліцензування — Ти згідний/на, що все, що ти створюєш на цьому сайті підпадає під Creative Commons Attribution License
        <a data-toggle="collapse" href="#collapseWhy" role="button" aria-expanded="false" aria-controls="collapseWhy">
          <strong>Чому?</strong>
        </a></li>
        <div class="alert alert-info  collapse" id="collapseWhy" role="alert">

            <p>Інформація, яка розміщена на сайті, поширюється у відповідності до <a href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International</a>  Міжнародної ліцензії.
              Вона передбачає, що інформація може бути використана, поширена будь-ким. </p>

            <p>Кожен, хто долучається до створення чи редагування політик також погоджується, що їхня робота буде ліцензована у відповідності до
              <a href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International</a> Міжнародної ліцензії.</p>

        </div>
      </ul>

    </div>
        <% end %>



  <div class="actions">
    <%  if controller.action_name == "new"  %>
        <%= form.submit "Зберегти проект політики"%>
    <% else %>
        <%= form.submit "Зберегти зміни"%>
        <%= form.submit "Зберегти проект політики", class: "no_act" %>
    <% end %>
    <%= link_to 'Скасувати', policies_path %>
  </div>
<% end %>

app/views/policies/_index.erb
<div class="list-filters clearfix">
  <% if params[:policies].blank? %>
  <ul class="sort-first text-uppercase d-none d-sm-none d-md-none d-lg-block">
    <li <%= params[:filter].nil? ? "class=disabled": "" %> ><%= link_to "Опубліковані політики", params.merge(filter: nil), remote: true %></li>
    <li <%= params[:filter] == "provisional" ? "class=disabled": "" %> ><%= link_to "Проекти політик", params.merge(filter: :provisional), remote: true %></li>
    <%= link_to 'СТВОРИТИ НОВУ ПОЛІТИКУ', new_policy_path, class: "new-policy"  %>
  </ul>
   <select class="mobile_select d-block d-md-none" onchange="window.location.href=this.value;">
      <option value="<%=policies_path(params.merge(filter: :nil))%>">Опубліковані політики</option>
      <option <%= params[:filter] == "provisional" ? 'selected="selected"': ''%> value="<%=policies_path(params.merge(filter: :provisional))%>">Проекти політик</option>
      <option <%= params[:filter] == "p" ? 'selected="selected"': ''%> value="<%= new_policy_path %>">СТВОРИТИ НОВУ ПОЛІТИКУ</option>
  </select>

  <% end %>
  <div id="list_policy">
  <%= render 'policy',  policies: @policies %>
  </div>
</div>

app/views/policies/_mp.erb
<div class="row">
  <% unless @policy.policy_divisions.size == 0 %>
  <% mps.each do |mp| %>
      <%= link_to show_person_policy_path(mp.mp.url_name, @policy.id), class: "" do %>
      <div class="card-mp">
        <div class="img" style="background-image: url('/image/<%= mp.deputy_id %>.png');"></div>
<!--          <img  src="/image/<%#= mp.mp.deputy_id %>.png" alt="<%#=  mp.mp.full_name  %>">-->
          <p><%=mp.mp.full_name %></p>
      </div>
         <% end %>
  <% end %>
  <% end %>
</div>

app/views/policies/_policy.erb
<div class="container">
    <div class="row">
        <% if policies.blank? %>
          <div class="col col 12 center-justified">
            <p class="text-center">Наданий момент не має даних політик</p>
          </div>
        <% else %>
          <% policies.each do |p| %>
          <div class="col-12 col-md-6" style="margin-bottom: 25px">
              <%= link_to policy_path(p.id), class: "" do %>
              <div class="col-12 pull-right card" style="padding: 25px 30px">
                  <div class="row text-uppercase">

                  </div>
                  <div class="row card-text">
                      <p><%=  p.name  %></p>
                  </div>
                  <div class="row check">
                      <div class="col-6 text-uppercase float-left">
                          <p class="checkin">оновлення даних</p>
                           <% if !p.policy_divisions.blank? %>
                          <p class="card-percent"><%= p.policy_divisions.last.updated_at.strftime('%d.%m.%Y / %H:%M') %></p>
                            <% else %>
                            <p class="card-percent"><%= p.updated_at.strftime('%d.%m.%Y / %H:%M') %></p>
                            <% end %>
                      </div>
                      <div class="col-6 text-uppercase">
                          <p class="checkin">голосувань</p>
                          <p class="card-percent"><%= p.policy_divisions.size %></p>
                      </div>

                  </div>
              </div>
              <% end %>
          </div>
          <% end %>
        <% end %>
    </div>
</div>
<% unless policies.last_page? or policies.blank? %>
    <% if controller.controller_path=="people" %>
    <%= link_to('<h4 class="text-uppercase text-center">Більше <i class="fa fa-arrow-circle-right fa-2x" aria-hidden="true"></i></h4>'.html_safe, people_policy_path(params.merge(page: policies.current_page + 1)), remote: true, id: "load_more_link" ) %>
     <% elsif controller.controller_path=="policy_divisions" %>
        <%= link_to('<h4 class="text-uppercase text-center">Більше <i class="fa fa-arrow-circle-right fa-2x" aria-hidden="true"></i></h4>'.html_safe, get_policy_division_path(params.merge(page: policies.current_page + 1)), remote: true, id: "load_more_link" ) %>
     <% else %>
        <%= link_to('<h4 class="text-uppercase text-center">Більше <i class="fa fa-arrow-circle-right fa-2x" aria-hidden="true"></i></h4>'.html_safe, policies_next_path(params.merge(page: policies.current_page + 1)), remote: true, id: "load_more_link" ) %>
    <% end %>
<% end %>

app/views/policies/_voted.erb
<div class="container">
    <div class="row">
        <% division.each do |d| %>
        <div class="col-12 col-md-6" style="margin-bottom: <%=  controller.action_name == "edit" ? "120" : "25"  %>px">
            <%= link_to divisions_show_path(d.division.date, d.division.number), class: "" do %>
            <div class="col-12 pull-right card" style="padding: 25px 30px">
                <div class="row text-uppercase" style="justify-content: space-between;">
                    <div class="approve "><i class="fa <%=  d.division.result == "Прийнято" ? "fa-check-circle" : "fa-times-circle"  %>" aria-hidden="true"></i> <%= d.division.result %></div>
                    <div class="card-date"><%= d.division.date.strftime('%d.%m.%Y') %>, <%= Time.parse(d.division.clock_time).strftime('%H:%M') %> </div>
                </div>
                <div class="row card-text">
                    <p><%=  d.division.name  %></p>
                </div>
                <div class="row check">
                    <div class="col-6 col-md-4 text-uppercase float-left">
                        <p class="checkin">присутність</p>
                        <p class="card-percent"><%= fraction_to_percentage_display(d.division.division_info.attendance_division) %></p>
                    </div>
                    <div class="col-6 col-md-4 text-uppercase" style="margin-bottom: 30px;">
                        <p class="checkin">проти фракції</p>
                        <p class="card-percent"><%= d.division.division_info.rebellions %>  голосувань</p>
                    </div>

                    <div class="col-6 offset-6 offset-md-0 col-md-4  text-uppercase float-right" style="top: -30px;color:#000;font-size: 8px;line-height: 18px;">
                      <!--<p class="checkin"></p>-->
                      <%= result_support(d.support) %>
                    <!--</div>
                    <div class="col-12 col-md-4 text-uppercase" style="color:#000;font-size: 8px;line-height: 18px;">-->
                    </div>

                </div>

            </div>
            <% end %>
          <%  if controller.action_name == "edit"  %>
              <div class="actions">
                <%= link_to 'Вилучити з політики', d, method: :delete, data: { confirm: 'Are you sure?' } , style: "margin:20px;"%>
                <%= link_to 'Змінити позицію щодо політики', edit_policy_division_path(d) %>
              </div>
          <% end %>
        </div>

        <% end %>
    </div>
</div>

app/views/policies/edit.html.erb
<% content_for :title, "Редагувати політику — Як Голосує Твій Депутат?" %>

<div id="first-block" class="container people">
  <h1 class="text-uppercase center-justified text-xs-center">Редагувати політику</h1>
</div>

<div class="container">
  <div id="policy">
    <%= render('edit') %>
  </div>


</div>



<%#= link_to 'Show', @policy %> 
<%#= link_to 'Back', policies_path %>

app/views/policies/edit.js.erb
window.history.pushState("", "", "<%= request.fullpath  %>");
$("#policy").html("<%= escape_javascript(render('edit')) %>");

app/views/policies/history.js.erb
$("#load_more_link").remove();
$("#list_history").append("<%= escape_javascript(render('layouts/history')) %>");

app/views/policies/index.html.erb
<% content_for :title, "Політики — Як Голосує Твій Депутат?" %>

<div id="first-block" class="container people">
  <h1 class="text-uppercase center-justified text-xs-center">Політики <%= Settings.name_rada %></h1>
  <div class="row">
    <%= form_tag(policies_path, method: "get", class: "col-8 form-inline mt-2 mt-md-0 push-2", id: "search-main", remote: true  ) do  %>
                          <span class="fa-stack">
                            <i class="fa fa-search fa-stack-1x fa-inverse" aria-hidden="true"></i>
                          </span>
        <%= text_field_tag(:policies, params[:policies] , class: "form-control mr-sm-2" , placeholder: "Шукати по заголовку" ) %>
        <!--<i class="fa fa-chevron-down arrow-icon" aria-hidden="true"></i>-->
    <% end %>
  </div>
  <div id="policy">
    <%= render(:partial => 'index', :locals => {:policies => @policies}) %>
  </div>
</div>


        <td><%#= link_to 'Show', policy %></td>
        <td><%#= link_to 'Edit', edit_policy_path(policy) %></td>
        <td><%#= link_to 'Destroy', policy, method: :delete, data: { confirm: 'Are you sure?' } %></td>

app/views/policies/new.html.erb
<% content_for :title, "Створити нову політику — Як Голосує Твій Депутат?" %>

<div id="divisionshow" class="container">
  <h1 class="text-uppercase center-justified text-xs-center">Створити нову політику</h1>
</div>
<div class="container-fluid team">
  <div class="container">
    <p>Додай нову політику, написавши два твердження.
      Пиши опис просто, щоб можна було легко зрозуміти, а також політично незаангажовано
    </p>
    <a data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
      <strong>Корисні поради щодо створення політик</strong>
    </a>
    <div class="collapse" id="collapseExample">

      <strong>Пиши так, щоб було якомога менше інтерпретацій.</strong>
      <p>“За здорових дітей” - поганий приклад для опису політики, тому що потрібно специфікувати голосування, які відносяться до неї. А це опис дуже загальний. “За підвищення рівня фінансування вищих навчальних закладів” - хороший приклад, тому що легко зорієнтуватись, як голосував депутат.</p>

      <strong>Групуй правильно.</strong>
      <p>Ціль створення політики — це зібрати в одному місці всі голосування по темі. Але якщо потрібно (інший аспект або ситуація), то можна її розділити, або ж, навпаки, одне голосування може бути в кількох політиках.</p>

      <strong>Не повторюйся.</strong>
      <p>Перевіряй сторінку політики, щоб побачити, які вже політики існують. Якщо ж голосування проти політики, то не потрібно створювати нову. Просто можна підв'язати відповідні голосування, зазначивши, чи це в підтримку чи проти політики.</p>

      <strong>Перевір, чи відповідне голосування існує.</strong>
      <p>Кожна політика має мати голосування, які вже розглядались міською радою. Тобто, якщо існує голосування, але
        воно ще не було на розгляді (за включення його в порядок денний, за нього не голосували), то його не можна
        підв'язати до політики.</p>

      <strong>Не соромся.</strong>
      <p>Ці політики належать всім. Якщо ти думаєш, що політика неправильно сформована, або ж не ті голосування
        підв'язані, виправ це.</p>
    </div>

  </div>

</div>
<div class="container">

<%= render 'form', policy: @policy %>


</div>

app/views/policies/policy.js.erb
$("#load_more_link").remove();
$("#list_policy").append("<%= escape_javascript(render(:partial => 'policy', :locals => {policies: @policies  })) %>");

app/views/policies/show.html.erb
<% content_for :title, "Політика — Як Голосує Твій Депутат?" %>

<div id="divisionshow" class="container">
  <h1 class="text-uppercase center-justified text-xs-center">Політика <%= Settings.name_rada %></h1>
</div>
<div class="container-fluid team">
  <div class="container">
    <div class="row">
    <div class="col-12 col-lg-9">
     <h2><strong><%= @policy.name %></strong></h2>
      <p><%= @policy.description %></p>
    </div>
    <div class="col-12 col-lg-3">
       <ul class="social row pull-right text-uppercase">
            <li class="col-12">
              <%= link_to edit_policy_path(@policy) do %>
                    <span class="fa-stack ">
                      <i class="fa fa-square-o fa-stack-2x"></i>
                      <i class="fa  fa-download  fa-stack-1x"></i>
                    </span>Редагувати
              <% end %>
            </li>
            <li class="col-12">
              <%= link_to policy_path(@policy, history: 1) do %>
                    <span class="fa-stack ">
                      <i class="fa fa-square-o fa-stack-2x"></i>
                      <i class="fa  fa-download  fa-stack-1x"></i>
                    </span>Історія редагувань
              <% end %>
            </li>
        </ul>    
    </div>
    </div>
  </div>
</div>
  <% if params[:history]=="1" %>
      <div id="divisionshow" class="container">
        <h2 class="text-uppercase center-justified text-xs-center">Історія редагувань</h2>
      </div>
      <div class="container">
        <div id="list_history">
     <%= render 'layouts/history' %>
        </div>
      </div>
  <% else %>
    <div id="detal">
    <%= render "show" %>
  <% end %>
</div>





<%#= link_to 'Back', policies_path %>